version: '3.7'
services:
  spark-master:
    container_name: ${SPARK_MASTER_CONTAINER_NAME}
    hostname: ${SPARK_MASTER_HOST_NAME}
    image: yellow-cab/spark
    environment:
    - SPARK_MODE=master
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
    volumes:
    - ../spark-scripts:/spark-scripts
    - ../scripts:/scripts
    - ../logs:/tmp
    - ../data:/data
    ports:
    - ${SPARK_MASTER_UI}:8080
    - ${SPARK_MASTER_PORT}:7077

  spark-worker-1:
    container_name: ${SPARK_WORKER_CONTAINER_NAME}-1
    image: yellow-cab/spark
    environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://${SPARK_MASTER_HOST_NAME}:${SPARK_MASTER_PORT}
    - SPARK_WORKER_MEMORY=8G
    - SPARK_WORKER_CORES=4
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
    volumes:
    - ../spark-scripts:/spark-scripts
    - ../scripts:/scripts
    - ../logs:/tmp
    - ../data:/data
    depends_on:
    - spark-master

networks:
  default:
    name: yellow-cab-network
    external: true